/**
 * Riccardo Giannetto  API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PaginatedUserActivityList } from '../model/models';
import { UserActivity } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AnalyticsActivitiesCreateRequestParams {
    userActivity: UserActivity;
}

export interface AnalyticsActivitiesDestroyRequestParams {
    id: number;
}

export interface AnalyticsActivitiesListRequestParams {
    limit?: number;
    offset?: number;
}

export interface AnalyticsActivitiesPartialUpdateRequestParams {
    id: number;
    userActivity: UserActivity;
}

export interface AnalyticsActivitiesRetrieveRequestParams {
    id: number;
}

export interface AnalyticsActivitiesUpdateRequestParams {
    id: number;
    userActivity: UserActivity;
}


export interface AnalyticsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /analytics/activities/
* @param requestParameters
     */
    analyticsActivitiesCreate(requestParameters: AnalyticsActivitiesCreateRequestParams, extraHttpRequestParams?: any): Observable<UserActivity>;

    /**
     * 
     * 
     * @endpoint delete /analytics/activities/{id}/
* @param requestParameters
     */
    analyticsActivitiesDestroy(requestParameters: AnalyticsActivitiesDestroyRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /analytics/activities/
* @param requestParameters
     */
    analyticsActivitiesList(requestParameters: AnalyticsActivitiesListRequestParams, extraHttpRequestParams?: any): Observable<PaginatedUserActivityList>;

    /**
     * 
     * 
     * @endpoint patch /analytics/activities/{id}/
* @param requestParameters
     */
    analyticsActivitiesPartialUpdate(requestParameters: AnalyticsActivitiesPartialUpdateRequestParams, extraHttpRequestParams?: any): Observable<UserActivity>;

    /**
     * 
     * 
     * @endpoint get /analytics/activities/{id}/
* @param requestParameters
     */
    analyticsActivitiesRetrieve(requestParameters: AnalyticsActivitiesRetrieveRequestParams, extraHttpRequestParams?: any): Observable<UserActivity>;

    /**
     * 
     * 
     * @endpoint put /analytics/activities/{id}/
* @param requestParameters
     */
    analyticsActivitiesUpdate(requestParameters: AnalyticsActivitiesUpdateRequestParams, extraHttpRequestParams?: any): Observable<UserActivity>;

}
