/**
 * Riccardo Giannetto  API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { PaginatedUserActivityList } from '../model/models';
import { UserActivity } from '../model/models';

import { Configuration } from '../configuration';

export interface AnalyticsActivitiesCreateRequestParams {
  userActivity: UserActivity;
}

export interface AnalyticsActivitiesListRequestParams {
  limit?: number;
  offset?: number;
}

export interface AnalyticsActivitiesRetrieveRequestParams {
  id: number;
}

export interface AnalyticsServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   * ViewSet for viewing and creating user activities.
   * @endpoint post /analytics/activities/
   * @param requestParameters
   */
  analyticsActivitiesCreate(
    requestParameters: AnalyticsActivitiesCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<UserActivity>;

  /**
   *
   * ViewSet for viewing and creating user activities.
   * @endpoint get /analytics/activities/
   * @param requestParameters
   */
  analyticsActivitiesList(
    requestParameters: AnalyticsActivitiesListRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<PaginatedUserActivityList>;

  /**
   *
   * ViewSet for viewing and creating user activities.
   * @endpoint get /analytics/activities/{id}/
   * @param requestParameters
   */
  analyticsActivitiesRetrieve(
    requestParameters: AnalyticsActivitiesRetrieveRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<UserActivity>;
}
