/**
 * Riccardo Giannetto  API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PaginatedUserActivityList } from '../model/models';
import { UserActivity } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AnalyticsUserActivityCreateRequestParams {
    userActivity: UserActivity;
}

export interface AnalyticsUserActivityListRequestParams {
    limit?: number;
    offset?: number;
}

export interface AnalyticsUserActivityRetrieveRequestParams {
    id: number;
}


export interface AnalyticsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * ViewSet for viewing and creating user activities.
     * @endpoint post /analytics/user-activity/
* @param requestParameters
     */
    analyticsUserActivityCreate(requestParameters: AnalyticsUserActivityCreateRequestParams, extraHttpRequestParams?: any): Observable<UserActivity>;

    /**
     * 
     * ViewSet for viewing and creating user activities.
     * @endpoint get /analytics/user-activity/
* @param requestParameters
     */
    analyticsUserActivityList(requestParameters: AnalyticsUserActivityListRequestParams, extraHttpRequestParams?: any): Observable<PaginatedUserActivityList>;

    /**
     * 
     * ViewSet for viewing and creating user activities.
     * @endpoint get /analytics/user-activity/{id}/
* @param requestParameters
     */
    analyticsUserActivityRetrieve(requestParameters: AnalyticsUserActivityRetrieveRequestParams, extraHttpRequestParams?: any): Observable<UserActivity>;

}
