/**
 * Riccardo Giannetto  API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Category } from '../model/models';
import { Page } from '../model/models';
import { PaginatedCategoryList } from '../model/models';
import { PaginatedPageList } from '../model/models';
import { PaginatedPostPreviewList } from '../model/models';
import { Post } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface BlogCategoriesListRequestParams {
    limit?: number;
    offset?: number;
}

export interface BlogCategoriesRetrieveRequestParams {
    id: number;
}

export interface BlogPagesListRequestParams {
    limit?: number;
    offset?: number;
}

export interface BlogPagesRetrieveRequestParams {
    tag: string;
}

export interface BlogPostsListRequestParams {
    categoriesName?: string;
    ordering?: string;
    page?: number;
    pageSize?: number;
    search?: string;
}

export interface BlogPostsRetrieveRequestParams {
    id: number;
}


export interface BlogServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * API endpoint that allows groups to be viewed or edited.
     * @endpoint get /blog/categories
* @param requestParameters
     */
    blogCategoriesList(requestParameters: BlogCategoriesListRequestParams, extraHttpRequestParams?: any): Observable<PaginatedCategoryList>;

    /**
     * 
     * API endpoint that allows groups to be viewed or edited.
     * @endpoint get /blog/categories/{id}
* @param requestParameters
     */
    blogCategoriesRetrieve(requestParameters: BlogCategoriesRetrieveRequestParams, extraHttpRequestParams?: any): Observable<Category>;

    /**
     * 
     * 
     * @endpoint get /blog/pages
* @param requestParameters
     */
    blogPagesList(requestParameters: BlogPagesListRequestParams, extraHttpRequestParams?: any): Observable<PaginatedPageList>;

    /**
     * 
     * 
     * @endpoint get /blog/pages/{tag}
* @param requestParameters
     */
    blogPagesRetrieve(requestParameters: BlogPagesRetrieveRequestParams, extraHttpRequestParams?: any): Observable<Page>;

    /**
     * 
     * 
     * @endpoint get /blog/posts
* @param requestParameters
     */
    blogPostsList(requestParameters: BlogPostsListRequestParams, extraHttpRequestParams?: any): Observable<PaginatedPostPreviewList>;

    /**
     * 
     * 
     * @endpoint get /blog/posts/{id}
* @param requestParameters
     */
    blogPostsRetrieve(requestParameters: BlogPostsRetrieveRequestParams, extraHttpRequestParams?: any): Observable<Post>;

}
