/**
 * Riccardo Giannetto Gallery API
 * API app riccardogiannetto.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ListPages200Response } from '../model/models';
import { Page } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ListPagesRequestParams {
    limit?: number;
    offset?: number;
}

export interface RetrievePageRequestParams {
    tag: string;
}


export interface BlogServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    listPages(requestParameters: ListPagesRequestParams, extraHttpRequestParams?: any): Observable<ListPages200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    retrievePage(requestParameters: RetrievePageRequestParams, extraHttpRequestParams?: any): Observable<Page>;

}
