/**
 * Riccardo Giannetto Gallery API
 * API app riccardogiannetto.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Gallery } from '../model/models';
import { ImageGallery } from '../model/models';
import { ListGalleries200Response } from '../model/models';
import { ListImageGalleries200Response } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface JpegImageGalleryRequestParams {
    id: string;
    width: string;
}

export interface ListGalleriesRequestParams {
    page?: number;
    pageSize?: number;
    title?: string;
    search?: string;
    ordering?: string;
}

export interface ListImageGalleriesRequestParams {
    page?: number;
    pageSize?: number;
    gallery?: string;
    search?: string;
    ordering?: string;
}

export interface RetrieveGalleryRequestParams {
    id: string;
    title?: string;
    search?: string;
    ordering?: string;
}

export interface RetrieveImageGalleryRequestParams {
    id: string;
    gallery?: string;
    search?: string;
    ordering?: string;
}


export interface PortfolioServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    jpegImageGallery(requestParameters: JpegImageGalleryRequestParams, extraHttpRequestParams?: any): Observable<ImageGallery>;

    /**
     * 
     * 
* @param requestParameters
     */
    listGalleries(requestParameters: ListGalleriesRequestParams, extraHttpRequestParams?: any): Observable<ListGalleries200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    listImageGalleries(requestParameters: ListImageGalleriesRequestParams, extraHttpRequestParams?: any): Observable<ListImageGalleries200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    retrieveGallery(requestParameters: RetrieveGalleryRequestParams, extraHttpRequestParams?: any): Observable<Gallery>;

    /**
     * 
     * 
* @param requestParameters
     */
    retrieveImageGallery(requestParameters: RetrieveImageGalleryRequestParams, extraHttpRequestParams?: any): Observable<ImageGallery>;

}
