/**
 * Riccardo Giannetto  API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Gallery } from '../model/models';
import { ImageGallery } from '../model/models';
import { PaginatedGalleryList } from '../model/models';
import { PaginatedImageGalleryList } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface PortfolioGalleriesListRequestParams {
    ordering?: string;
    page?: number;
    pageSize?: number;
    search?: string;
    title?: string;
}

export interface PortfolioGalleriesRetrieveRequestParams {
    id: number;
}

export interface PortfolioImagesListRequestParams {
    gallery?: number;
    ordering?: string;
    page?: number;
    pageSize?: number;
    search?: string;
}

export interface PortfolioImagesRetrieveRequestParams {
    id: number;
}

export interface PortfolioImagesWidthRetrieveRequestParams {
    id: number;
    width: string;
}


export interface PortfolioServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    portfolioGalleriesList(requestParameters: PortfolioGalleriesListRequestParams, extraHttpRequestParams?: any): Observable<PaginatedGalleryList>;

    /**
     * 
     * 
* @param requestParameters
     */
    portfolioGalleriesRetrieve(requestParameters: PortfolioGalleriesRetrieveRequestParams, extraHttpRequestParams?: any): Observable<Gallery>;

    /**
     * 
     * 
* @param requestParameters
     */
    portfolioImagesList(requestParameters: PortfolioImagesListRequestParams, extraHttpRequestParams?: any): Observable<PaginatedImageGalleryList>;

    /**
     * 
     * 
* @param requestParameters
     */
    portfolioImagesRetrieve(requestParameters: PortfolioImagesRetrieveRequestParams, extraHttpRequestParams?: any): Observable<ImageGallery>;

    /**
     * 
     * 
* @param requestParameters
     */
    portfolioImagesWidthRetrieve(requestParameters: PortfolioImagesWidthRetrieveRequestParams, extraHttpRequestParams?: any): Observable<ImageGallery>;

}
