/**
 * Riccardo Giannetto Gallery API
 * API app riccardogiannetto.com
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Category { 
    readonly id?: number;
    readonly posts?: string;
    name: string;
}

