/**
 * Riccardo Giannetto  API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Serializer for the Gallery model.  This serializer provides a complete representation of a Gallery instance, including its ID, URL, author string representation, and hyperlinks to associated images. It handles serialization for the API\'s gallery endpoints.
 */
export interface Gallery { 
    readonly url: string;
    id: number;
    readonly author: string;
    images: Array<string>;
    title: string;
    description: string;
    tag: string;
    readonly created_at: string;
    readonly updated_at: string;
}

