/**
 * Riccardo Giannetto Gallery API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Gallery { 
    readonly url?: string;
    id: number;
    readonly author?: string;
    readonly images?: Array<string>;
    title: string;
    description: string;
    tag: string;
    readonly created_at?: string;
    readonly updated_at?: string;
}

