/**
 * Riccardo Giannetto  API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageGallerySlug } from './imageGallerySlug';


/**
 * Serializer for ImageGallery location data.
 */
export interface ImageLocation { 
    readonly id: number;
    title: string;
    latitude?: number | null;
    longitude?: number | null;
    slug?: ImageGallerySlug;
    readonly thumbnail: string;
}

