/**
 * Riccardo Giannetto  API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Serializer for the ImageGallery model.  This serializer handles the serialization of ImageGallery instances, converting them to JSON format and vice-versa. It includes a hyperlinked identity field for the detail view and a string representation of the author.  Attributes:     url (HyperlinkedIdentityField): URL to the detail view of the image.     author (StringRelatedField): String representation of the author.
 */
export interface ImageGallery { 
    readonly url: string;
    readonly author: string;
    title: string;
    slug?: string;
    image: string;
    tags?: Array<string>;
    width: number;
    height: number;
    readonly created_at: string;
    readonly updated_at: string;
    camera_model?: string;
    lens_model?: string;
    iso_speed?: number | null;
    aperture_f_number?: number | null;
    shutter_speed?: number | null;
    focal_length?: number | null;
    artist?: string;
    copyright?: string;
    latitude?: number | null;
    longitude?: number | null;
    altitude?: number | null;
    location?: string;
    date?: string | null;
    gallery: string;
}

