/**
 * Riccardo Giannetto Gallery API
 * API app riccardogiannetto.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ImageGallery { 
    readonly url?: string;
    readonly author?: string;
    title: string;
    image: Blob;
    width: number;
    height: number;
    readonly created_at?: string;
    readonly updated_at?: string;
    gallery: string;
}

