/**
 * Riccardo Giannetto  API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ImageGallery { 
    readonly url: string;
    readonly author: string;
    title: string;
    image: string;
    width: number;
    height: number;
    readonly created_at: string;
    readonly updated_at: string;
    camera_model?: string;
    lens_model?: string;
    iso_speed?: number | null;
    aperture_f_number?: number | null;
    shutter_speed?: number | null;
    focal_length?: number | null;
    artist?: string;
    copyright?: string;
    date?: string | null;
    gallery: string;
}

