/**
 * Riccardo Giannetto Gallery API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Gallery } from './gallery';


export interface ListGalleries200Response { 
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Gallery>;
}

