/**
 * Riccardo Giannetto Gallery API
 * API app riccardogiannetto.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Page } from './page';


export interface ListPages200Response { 
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Page>;
}

