/**
 * Riccardo Giannetto Gallery API
 * API app riccardogiannetto.com
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Category } from './category';


export interface ListCategories200Response { 
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Category>;
}

