/**
 * Riccardo Giannetto Gallery API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PageAuthor { 
    /**
     * Obbligatorio. 150 caratteri o meno.Solo lettere, cifre e @/./+/-/_
     */
    username: string;
}

