/**
 * Riccardo Giannetto  API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface Page { 
    readonly id: number;
    readonly url: string;
    tag: string;
    readonly author: User;
    title: string;
    body: string;
    readonly created_at: string;
}

