/**
 * Test App API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageGallery } from './imageGallery';


export interface PaginatedImageGalleryList { 
    count: number;
    next?: string;
    previous?: string;
    results: Array<ImageGallery>;
}

