/**
 * Riccardo Giannetto  API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserActivity } from './userActivity';


export interface PaginatedUserActivityList { 
    count: number;
    next?: string;
    previous?: string;
    results: Array<UserActivity>;
}

