/**
 * Test App API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Gallery } from './gallery';


export interface PaginatedGalleryList { 
    count: number;
    next?: string;
    previous?: string;
    results: Array<Gallery>;
}

