/**
 * Riccardo Giannetto  API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostPreview } from './postPreview';


export interface PaginatedPostPreviewList { 
    count: number;
    next?: string;
    previous?: string;
    results: PostPreview[];
}

