/**
 * Riccardo Giannetto Gallery API
 * API app riccardogiannetto.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageAuthor } from './pageAuthor';


export interface Post { 
    readonly id?: number;
    readonly url?: string;
    author?: PageAuthor;
    title: string;
    body: string;
    readonly created_at?: string;
    image?: Blob | null;
    categories: Array<string>;
    summary?: string;
}

