/**
 * Riccardo Giannetto  API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Serializer for UserActivity model.
 */
export interface UserActivity { 
    readonly id: number;
    readonly user: number | null;
    action: string;
    path?: string;
    method?: string;
    readonly ip_address: string | null;
    user_agent?: string | null;
    payload?: any | null;
    readonly timestamp: string;
}

