/**
 * Riccardo Giannetto  API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Serializer for the User model.
 */
export interface User { 
    /**
     * Obbligatorio. 150 caratteri o meno.Solo lettere, cifre e @/./+/-/_
     */
    username: string;
}

