# Generated by Django 6.0.1 on 2026-01-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_usersession_useractivity_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='device_fingerprint',
            field=models.CharField(blank=True, help_text='Hash of header-based device characteristics', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='tracking_id',
            field=models.CharField(blank=True, help_text='Persistent cookie ID for tracking across sessions', max_length=255, null=True),
        ),
    ]
