# Generated by Django 6.0.1 on 2026-01-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_usersession_device_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
