# Generated by Django 6.0.1 on 2026-01-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_usersession_latitude_usersession_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='device_fingerprint',
            field=models.CharField(blank=True, db_index=True, help_text='Hash of header-based device characteristics', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='tracking_id',
            field=models.CharField(blank=True, db_index=True, help_text='Persistent cookie ID for tracking across sessions', max_length=255, null=True),
        ),
    ]
