# Generated by Django 6.0.2 on 2026-02-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_alter_useractivity_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSPReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('document_uri', models.URLField(blank=True, db_index=True, max_length=500, null=True)),
                ('referrer', models.URLField(blank=True, max_length=500, null=True)),
                ('violated_directive', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('effective_directive', models.CharField(blank=True, max_length=255, null=True)),
                ('original_policy', models.TextField(blank=True, null=True)),
                ('blocked_uri', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=500, null=True)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('column_number', models.IntegerField(blank=True, null=True)),
                ('raw_report', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'CSP Report',
                'verbose_name_plural': 'CSP Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
