# Generated by Django 5.0.4 on 2024-05-03 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_imagegallery_gallery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'verbose_name_plural': 'images'},
        ),
        migrations.AddIndex(
            model_name='imagegallery',
            index=models.Index(fields=['title'], name='gallery_ima_title_be2862_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegallery',
            index=models.Index(fields=['author'], name='gallery_ima_author__7dbca4_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegallery',
            index=models.Index(fields=['gallery'], name='gallery_ima_gallery_8f3680_idx'),
        ),
    ]
