# Generated by Django 5.0.4 on 2024-05-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_imagegallery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
