# Generated by Django 5.0.4 on 2024-05-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_imagegallery_height_alter_imagegallery_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
