# Generated by Django 5.0.4 on 2024-05-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_alter_imagegallery_height_alter_imagegallery_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
