# Generated by Django 5.0.5 on 2024-05-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_imagegallery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='aperture_f_number',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='artist',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='camera_model',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='copyright',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='exposure_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='focal_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='iso_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='lens_model',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
