# Generated by Django 5.0.5 on 2024-05-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_imagegallery_aperture_f_number_imagegallery_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
