# Generated by Django 6.0.1 on 2026-01-18 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_rename_exposure_time_imagegallery_shutter_speed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gallery',
            name='gallery_gal_tag_f938e4_idx',
        ),
        migrations.RemoveIndex(
            model_name='imagegallery',
            name='gallery_ima_author__7dbca4_idx',
        ),
        migrations.RemoveIndex(
            model_name='imagegallery',
            name='gallery_ima_gallery_8f3680_idx',
        ),
        migrations.AddIndex(
            model_name='imagegallery',
            index=models.Index(fields=['created_at'], name='gallery_ima_created_53be8b_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegallery',
            index=models.Index(fields=['date'], name='gallery_ima_date_fd02dc_idx'),
        ),
    ]
