# Generated by Django 6.0.1 on 2026-01-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_imagegallery_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='location',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
