# Generated by Django 6.0.1 on 2026-02-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_imagegallery_altitude_imagegallery_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'galleries'},
        ),
    ]
