# Generated by Django 6.0.2 on 2026-02-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_alter_gallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
