# Generated by Django 6.0.2 on 2026-02-17 05:25

from django.db import migrations
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    ImageGallery = apps.get_model('gallery', 'ImageGallery')
    for image in ImageGallery.objects.all():
        if not image.slug:
            image.slug = slugify(image.title)
            # Ensure slug is unique if needed by appending id
            original_slug = image.slug
            count = 1
            while ImageGallery.objects.filter(slug=image.slug).exclude(pk=image.pk).exists():
                image.slug = f"{original_slug}-{count}"
                count += 1
            image.save()

class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_imagegallery_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs),
    ]
