# Generated by Django 6.0.2 on 2026-02-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_auto_20260217_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
