# Generated by Django 6.0.1 on 2026-02-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_page_blog_page_tag_a9d769_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageupload',
            options={'verbose_name_plural': 'Image uploads'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='imageupload',
            unique_together=set(),
        ),
    ]
